version: '3'

services:
  dailyjob_server:
    image: dailyjob_server
    build: .
    user: yeboyebo
    restart: always
    working_dir: /src/app/
    environment:
      - TZ=Europe/Amsterdam
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
    env_file:
      - ./.env
    ports:
      - "${PORT}:8000"
    extra_hosts:
      - "dbhost:${DBHOST}"
    volumes:
      - .:/src
      - ${PINEBOODIR}:/pineboo/pineboo
      - ${MODULESDIR}:/pineboo/modules
      - ${IMAGESVOL}:/static/images
      - /run/cups/cups.sock:/run/cups/cups.sock
      - /etc/cups/cupsd.conf:/etc/cups/cupsd.conf
    command: python3 manage.py runserver 0.0.0.0:8000 --noreload
    networks:
      app_network:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.${DOCKER_IP}.0.0/16
