version: '3'

services:
  django:
    image: django
    build: .
    user: juanma
    restart: always
    working_dir: /src/app/
    depends_on:
      - redis
    links:
      - redis
    environment:
      - TZ=Europe/Amsterdam
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
    env_file:
      - ./.env
    ports:
      - "${PORT}:8000"
    extra_hosts:
      - "dbhost:${DBHOST}"
    volumes:
      - .:/src
      - ${PINEBOODIR}:/pineboo/pineboo
      - ${MODULESDIR}:/pineboo/modules
    command: python3 manage.py runserver 0.0.0.0:8000
    networks:
      app_network:

  redis:
    image: redis:latest
    restart: always        
    ports:
      - '6379:6379'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.${DOCKER_IP}.0.0/16